# Generated by Django 2.0 on 2017-12-18 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_web', '0004_students'),
    ]

    operations = [
        migrations.DeleteModel(
            name='student_info',
        ),
        migrations.DeleteModel(
            name='students',
        ),
    ]
