# Generated by Django 2.0 on 2017-12-18 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_web', '0006_students_students_info'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='students_info',
            new_name='student_info',
        ),
    ]
