# Generated by Django 2.0 on 2017-12-18 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_web', '0007_auto_20171218_1522'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='student_info',
            new_name='students_detail',
        ),
    ]
