# Generated by Django 2.0 on 2017-12-18 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_web', '0010_auto_20171218_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='students_detail',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
